### ISSUE TITLE
Redirect from https://msusicky.github.io/ockovani-covid/ to https://ockovani.opendatalab.cz/

### ISSUE THREAD

**Issue by VojtaStanek** [msusicky/ockovani-covid#126]
Although it probably is not possible to set up HTTP redirect following meta tag should do the same:

```
<meta http-equiv="refresh" content="0; URL=https://ockovani.opendatalab.cz/">
```

This would also be better for SEO since [google understands it](https://developers.google.com/search/docs/advanced/crawling/special-tags).

**Comment by msusicky** [comment]
Our plan is to keep the current "old page" for some days and then push redirect as a index page. Other pages will remain.

**Comment by jan-stanek** [comment]
It took little bit longer than some days, but done :-)
