### ISSUE TITLE
Search by 7 day ratio, age, profession, vaccine types

### ISSUE THREAD

**Issue by AtomistaCZ** [msusicky/ockovani-covid#138]
Vyhledávání míst podle 7 denní úspěšnosti podle kritérií.
Příklad:
Pedagog, věk 50-54 preferující Pfizer

Vyhledávání dle: věk, povolání

Výsledkem je seznam míst seřazený od nejvyšší 7 denní úspěšnosti přidělení termínu v zadané kategorii (povolání, věk). Ve výsledcích budou u očkovacích center navíc sloupce s počty dávek pro různé druhy vakcín.

**Comment by jan-stanek** [comment]
Neaktuální
