### ISSUE TITLE
Copy prd database to acc database periodically

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#159]

**Comment by jan-stanek** [comment]
@msusicky following command can be used, but maybe it's better to do it manually - acc database can have newer structure
`pg_dump -c ockovani_prd | psql ockovani_acc`

**Comment by msusicky** [comment]
workflow created, issue with tables that should not exist

**Comment by jan-stanek** [comment]
We are not going to drop another tables, it's ok to clean it manually in this case

**Comment by msusicky** [comment]
Ok, then closing
