### ISSUE TITLE
Kdy dostanu dávku?

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#172]
Z emailu:

Kalkulačka pro všechny: možnost zadat věk, kraj, tempo denního očkování první
dávkou a vypočíst, kdy se osoba dostane na řadu při daných parametrech

**Comment by msusicky** [comment]
Should be realized in JS. Input boxes: Vek, Kraj, rychlost ockovani, procento populace k ockovani.
It should compute some expected date.

**Comment by jan-stanek** [comment]
link to external calculator added in #240
