### ISSUE TITLE
Rychlost fronty

### ISSUE THREAD

**Issue by libor13** [msusicky/ockovani-covid#177]
Navrhuji přidat do přehledu očkovacích míst sloupec který by se spočítal jako poměr čekajících ve frontě/očkovaných 7 dní.
Vyjadřoval by jak rychle se fronta na daném očkovacím místě pohybuje.

**Comment by msusicky** [comment]
It is not as easy as it looks like. What is fronta. Should we sum the people that has already a vacc. date and add a people that are still waiting (should we count them twice)?
We cannot distinguish between people with 1st and 2nd dose.

My proposal:
Sum people with date and without date and divide this with vacc. speed for the last 7 days. Please, @vpokorny @jan-stanek @libor13  vote for my proposal or bring your new one :)
