### ISSUE TITLE
časové řady a dynamika front

### ISSUE THREAD

**Issue by vladv0719** [msusicky/ockovani-covid#178]
Stahujete pravidelně každodenní datové sady, které jsou statickým snímkem předešlého dne. 

Pokud si byste uchovávali historii údajů a ukazatelů počítaných ve vaší aplikaci, začnete si vytvářet vlastní časové řady. Na nich se pak dají sledovat dynamické jevy. Třeba dosavadní vývoj délky čekání na rezervaci (podle kategorií apod.). Ale také dělat odhady a prognózy do budoucna.

Bylo by takto možné také sledovat dynamiku front. Nejen kolik zájemců je momentálně ve frontě (tzn., jak je fronta dlouhá). Ale jak se fronta průběhem času plní na začátku (jak rychle a kolik se do fronty řadí nových zájemců) a jak se fronta na konci zkracuje (kolik ve frontě čekajících zájemců bylo úspěšně odbaveno tím, že jim byla umožněna registrace a případně kolik se opravdu registrovalo). Čili se dívat na fronty a sledovat, kolik zájemců jimi projde. Jak se fronty plní a zkracují a jaká je obslužnost v jednotlivých kategoriích zájemců.

**Comment by msusicky** [comment]
Víme, ale nejsou naše kapacity :) Aktuálně máme v developu nápočty metrik, které nás napadly, ale stále hledáme nové contributory...
Bez pomoci možná příští týden.

**Comment by jan-stanek** [comment]
Zatím přidán graf vývoje fronty

**Comment by msusicky** [comment]
Soo long it waits and now it is obsolete.
