### ISSUE TITLE
Red/yellow/green flag in queue 

### ISSUE THREAD

**Issue by jirmed** [msusicky/ockovani-covid#180]
The red/yellow/green flag color should be rather determined by the ration In queue/Inoculated last 7 days than by fixed tresholds (500,5000).

The fixed tresholds do not take in account very different capacities of the sites

I suggest tresholds 1 and 4 meaning green = queue up to one week, yellow = 1-4 weeks, red = longer

**Comment by msusicky** [comment]
It is duplicate to #177  -> we prepare a new approach to this, it will be soon available, so closing.
