### ISSUE TITLE
Graphs in statistics page

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#193]
Copied from another issue:
> could you add interactive chart for first table with daily details? Type vaccine, "přislo", "vyočkováno" and "rozdíl".

>@vpokorny just fyi -> it is a little bit tricky to compute that, just let me know if you will have any questions 

More graphs:
- [x] vaccines arrivals + usage
- [x] count of people in queue + count of people wating for 1st and 2nd dose (resuse graph from vaccination center, it can be added also to kraj)
- [ ] count of vaccinated doses + maximal capacity (resuse graph from vaccination center, it can be added also to kraj)
- [ ] cumulative count of vaccinated doses + cumulative count of arrived vaccines (not sure if it makes sense since arrived vaccines dataset is very dirty)
- [x] count of infected per 100 000 per age category + maybe deaths per 100 000 per age category + vaccinated % per age category (compare 80+, 70+ vs. rest) - aim is to show that vaccination works as expected
- [ ] new cases + deaths for kraje (reuse graph from statistics)

**Comment by msusicky** [comment]
Please, take a look at it.

**Comment by vpokorny** [comment]
Sure :-)

**Comment by jan-stanek** [comment]
Is it possible to use bar chart (arrived) and line chart (vaccinated) in one? Or some better solution. Now it contains too much lines and it will get worse with J&J.

**Comment by jan-stanek** [comment]
It should be possible to combine charts: https://plotly.com/python/graphing-multiple-chart-types/

Plotly is maybe too much "scientific", google charts seems to be more "human readable" (https://developers.google.com/chart/interactive/docs/gallery/combochart).

**Comment by vpokorny** [comment]
I tought about three line charts where each one contains three lines for each category 'prislo', 'vyockovano', 'rozdil'.

Is it necesary to have all the information in one chart?

**Comment by vpokorny** [comment]
Or there can be one chart with 3 subplots as described above.

**Comment by jan-stanek** [comment]
@msusicky @vpokorny Do we need some more, or we can close it?

**Comment by vpokorny** [comment]
Good question @jan-stanek - I have checked the charts and it seems that you have finished the rest. Correct?

**Comment by msusicky** [comment]
Closing
