### ISSUE TITLE
Add link to registration form

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#197]
Some people are asking if they can use our website also for the registration - maybe we should add at least the link to https://registrace.mzcr.cz/

**Comment by jan-stanek** [comment]
Link is already on main page, maybe we can put it also to the detail of each center?

**Comment by msusicky** [comment]
Yes, unfortunately there is no way how to fill this exact place to the official system.

**Comment by jan-stanek** [comment]
I know, but at least the universal link - #208 is a better solution
