### ISSUE TITLE
Dates handling

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#25]
It is necessary to solve date handling - insert new dates and delete old one ?

**Comment by msusicky** [comment]
Or better have active dates and select them  with an easy query?

**Comment by msusicky** [comment]
Fetch only > now ( added by @jan-stanek )
Maybe it will be not necessary to delete, maybe just to add a lot of dates and filter for next 30 days :)

**Comment by jan-stanek** [comment]
- [x] Fetch only > now
- [ ] add a lot of dates and filter for next 30 days
