### ISSUE TITLE
Queue statistics

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#278]
Provide global / or per kraj level / statistics for each group -> chronici, pedagogove, zdravotnici - that are in the queue.

**Comment by jan-stanek** [comment]
It's already there https://ockovani.opendatalab.cz/kraj/Jiho%C4%8Desk%C3%BD#registration

Or you mean without age category?

**Comment by msusicky** [comment]
Yes, exactly -> without age to see only complete sums.

**Comment by msusicky** [comment]
Done today
