### ISSUE TITLE
Email request - add column to stats

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#353]
Dobry den,

chtel bych se zeptat, zda by bylo mozne doplnit do tabulky
"Počty očkovaných dle věku" na strance Statistiky (https://ockovani.opendatalab.cz/statistiky) i sloupec
s pocty cekajicich na prvni davku podle vekove kategorie? Tyto udaje, spolu s ostatnimi, pak poskytnou
informaci o procentu lidi v dane vekove kategorii, kteri se uz zaregistrovali, a tim i o zajmu o ockovani podle veku.

**Comment by jan-stanek** [comment]
Chtěli jsme, ale rezervace bohužel nemají věk ani kategorii

**Comment by msusicky** [comment]
Ted se ale toto meni :)
