### ISSUE TITLE
Grupovani veku

### ISSUE THREAD

**Issue by waclaw66** [msusicky/ockovani-covid#371]
S tim, jak se pridavaji dalsi a dalsi prioritni skupiny se zobrazeni stava neprehlednym. Je mozne seskupit vek ruznych prioritnich skupin do jedne bunky tabulky, jako je 55-59 na obrazku?

![obrazek](https://user-images.githubusercontent.com/15554561/116521122-db8dc800-a8d3-11eb-83dc-4c3c2c2e8582.png)

**Comment by jan-stanek** [comment]
Vypadá to určitě přehledněji, ale je to trochu problematické v kombinaci s řazením tabulky

**Comment by msusicky** [comment]
Dovolím si aktuálně zavřít, dlouho neaktivní
