### ISSUE TITLE
Z emailu - praktici

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#393]
na strance
https://ockovani.opendatalab.cz/praktici
uvadite, jak ockuji praktici.

Domnivam se, ze je ferovejsi z datove sady UZIS "ockovaci-zarizeni"
vybrat jen zarizeni, jejichz zrizovatelem je fyzicka ci pravnicka osoba. I v tomtu vyberu zbyvaji i ne-praktici, ale uz tam nejsou pobocky OCM v jinem kraji a dalsi. Lepsi univerzalni klic me zatim nenapadl.

**Comment by jan-stanek** [comment]
done in #402
