### ISSUE TITLE
V popisku skupiny se nezobrazuje věk.

### ISSUE THREAD

**Issue by VojtaStanek** [msusicky/ockovani-covid#394]
Například na stránce: https://ockovani.opendatalab.cz/misto/5affc4c2-414a-4cd4-9a04-56647fa66eef#registration

![image](https://user-images.githubusercontent.com/4283010/117138478-5d399600-adab-11eb-94a0-44517eb1ff3e.png)

**Comment by jan-stanek** [comment]
Tyhle názvy skupin jsou přímo v datech, i s tím placeholderem, kterej se asi nahrazuje ve frontendu rezervčního systému

**Comment by msusicky** [comment]
Dneska doslo i emailem, ale jak je vyse, tohle my neovlivnime a zasahovat do nazvu kategorii nechceme.
