### ISSUE TITLE
Z twitteru - v prehledu kazdeho kraje umoznit vyber kategorie a na jejim zaklade ukazat hodnoty

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#400]
Realizace se vzhledem ke statickem webu bude muset realizovat dotahnutim vsech hodnot do stranky a nasledne temito daty filtrovat.

**Comment by jan-stanek** [comment]
Má to ještě cenu?

**Comment by jan-stanek** [comment]
Neaktuální
