### ISSUE TITLE
Remove Nejvýkonnější místo

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#406]
It does not make sense to have it anymore.
Change Nejvíce naočkovaných za den to last 7 days and add the ration between OCM and others.

**Comment by msusicky** [comment]
Remove Odhad dostupnosti vakcín pro věkové skupiny -> or maybe change it to the current status as a static.

**Comment by jan-stanek** [comment]
> 
> 
> Remove Odhad dostupnosti vakcín pro věkové skupiny -> or maybe change it to the current status as a static.

I would leave it there, at least for a while, it's not still obvious
