### ISSUE TITLE
Část klikací mapy nefunguje

### ISSUE THREAD

**Issue by jirijursa** [msusicky/ockovani-covid#446]
Pravděpodobně po přidání Výzvy přestalo fungovat klikání na Jihomoravský a Jihočeský kraj na mapě (úvodní stránka). 

Android/Chrome

**Comment by msusicky** [comment]
Ověřeno, ale funguje to při klikání na horní okraj daných krajů. Na win to vypadá, že spodní okraj JČ kraje je taky ignorovaný.

Díky za nahlášení!

**Comment by msusicky** [comment]
Prosím @jirijursa o test, u mě dobrý ;)

**Comment by jirijursa** [comment]
Funguje krásně. Děkuji za opravu i za celý tento webový počin 🙂

**Comment by msusicky** [comment]
Přehazuji kvůli finálnímu řešení.

**Comment by msusicky** [comment]
Fixed
