### ISSUE TITLE
Zobrazeni vekove hranice lidi, kteri se mohou volne registrovat na ockovani

### ISSUE THREAD

**Issue by kubic71** [msusicky/ockovani-covid#454]
**Describe the bug**
Na strance [https://ockovani.opendatalab.cz/kraj/Praha#registration](https://ockovani.opendatalab.cz/kraj/Praha#registration) se nezobrazuje minimalni vekova hranice nutna pro volnou registraci na ockovani

**To Reproduce**
1. Go to [https://ockovani.opendatalab.cz/kraj/Praha#registration](https://ockovani.opendatalab.cz/kraj/Praha#registration)
2. Najed mysi na prioritni skupinu lidi, kteri jsou ockovani na zaklade dosazeneho veku
4. Zobrazi se "Na základě dosaženého věku (aktuálně se mohou registrovat osoby starší {0} let)"

**Screenshot**
![image](https://user-images.githubusercontent.com/12272640/120441764-34de9080-c385-11eb-9de6-22ba8b745e1a.png)

**Comment by jirijursa** [comment]
Duplicitní: https://github.com/msusicky/ockovani-covid/issues/394

**Comment by kubic71** [comment]
sorry, nevsiml jsem si...
