### ISSUE TITLE
Zobrazování a filtrování očkovacích míst pro samoplátce

### ISSUE THREAD

**Issue by mikicz** [msusicky/ockovani-covid#455]
Ahoj, na přehledu očkovacích míst se objevila informace, zda očkovací místo bere samoplátce (viz screenshot)
![obrazek](https://user-images.githubusercontent.com/5583319/120554743-66457380-c3fa-11eb-816a-ccb058aab576.png)

V detailu na webu to není, je tam jen ten bezbariérový přístup. Rád bych si profiltroval místa, které samplátce berou, což na přehledu od ÚZISu nejde vůbec, ale na webu by to šlo, pokud by to umožnil - předpokládám, že zdrojový data to taky budou mít, nějak.

Šlo by to přidat do detailu očkovacích míst a do vyhledávače? Rád to klidně sám naimplementuju pokud to v datech skutečně je.

**Comment by mikicz** [comment]
Hm, tak jsem koukal na zdrojový data (https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/prehled-ockovacich-mist.csv) a tahle informace tam zatím není...

**Comment by msusicky** [comment]
Vypadá to, že se s tím pohne, uvidíme v nejbližších dnech

**Comment by mikicz** [comment]
Jop, co jsem četl tak by se ta registrace měla spustit do konce týdne, tak uvidíme kdy to skutečně bude (už taky říkali předtím že se to bude pouštět stejně jako kategorie 16-29) a jestli opendata budou ukazovat relevantní info. 

Moje nabídka, že to naimplementuju, furt platí, jakmile to bude ve zdrojových datech...

**Comment by mikicz** [comment]
Seznam je tady, v API to furt není https://registrace.mzcr.cz/samoplatci/ocm/

**Comment by msusicky** [comment]
Api není, ale pořád je tu stará dobrá metoda přepsání do csv manuálně. #country4thefuture

**Comment by mikicz** [comment]
Aha! Oni totiž přidali ty místa pro samoplátce jako separátní místa. Takže stačí vyhledat "samoplátci" a vyhodí to očkovací místa pro samoplátce

![obrazek](https://user-images.githubusercontent.com/5583319/121642961-85df3a80-ca91-11eb-8a52-f2df237b4a43.png)

**Comment by msusicky** [comment]
Jsem rád, že jsem to nezačal přepisovat. Kdyby se našel dobrovolník na vytvoření toho tlačítka, tak by to bylo fajn. Nebude to tolik práce a filtroval bych jen řetězec amopl - kdyby se měnilo to slovo...

**Comment by jan-stanek** [comment]
Vyskytuje se tam i "samoplátce" a "samoplátců"

**Comment by mikicz** [comment]
Zajímavý, teď jsem to refreshnul a změnily se zdrojový data? 
Tohle je screenshot z 8:48 
![obrazek](https://user-images.githubusercontent.com/5583319/121646564-be811300-ca95-11eb-9ab8-789c3bacbdf6.png)
a tohle je screenshot z 9:17
![obrazek](https://user-images.githubusercontent.com/5583319/121646631-cfca1f80-ca95-11eb-9b37-aac703605bf1.png)

Možná ty speciální místa použili nějak omylem?
