### ISSUE TITLE
Nesrovnalosti v procentech proockovanosti

### ISSUE THREAD

**Issue by MattyCZ** [msusicky/ockovani-covid#458]
Všiml jsem si, že ve statistikách udáváte dvě různé hodnoty proockovanosti. Jeda dneska říká 19% , druhá 15.4%. Jednou to totiž asi delite eligible populací, v druhém případě celkovou. Nechcete to nějak sjednotit? Also ockobot hlásí tu první

**Comment by msusicky** [comment]
Zajem o ockovani budeme ukazovat pro 18+ a pripravime PR pro zmenu na celou populaci. Odbornici mluvi stale o cele populaci, tak provedeme zmenu. 

- [ ] Odstranit datum doockovani z Ockobota
- [ ] Pridat novy tweet s informaci o tom, kdy nam dojdou lidi - dle 2. davek a pak zajmu o ockovani
- [ ] Zmena Ockobota na celou populaci

**Comment by msusicky** [comment]
Dnes vyreseno
