### ISSUE TITLE
Chybějící data - FNHK

### ISSUE THREAD

**Issue by hruskajiri** [msusicky/ockovani-covid#459]
Dobrý den,

u Fakultní nemocnice Hradec Králové, záložkou Statistiky chybějí od pátku 4. 6. 2021 některá data. Konkrétně položky Čekající na n-tou dávku a Dnešní kapacita n-té dávky ukazují čistou 0. Očkovací místo je v provozu.

Chybějící data se propisují i pod další záložky.

Odkaz na podstránku s FN HK: https://ockovani.opendatalab.cz/misto/57932100-0df4-472c-a015-d2b750df5b58.

Děkuji Vám za skvělou práci.

JH

**Comment by jan-stanek** [comment]
Dobrý den,
díky za upozornění, problém jsme nahlásili.

JS
