### ISSUE TITLE
špatný render v tooltipu v statistikách

### ISSUE THREAD

**Issue by MattyCZ** [msusicky/ockovani-covid#462]
**Describe the bug**
Při hoveru v statistikách v políčku "Na základě dosaženého věku" je v tooltipu {0}

**To Reproduce**
1. Go to https://ockovani.opendatalab.cz/statistiky
2. Scroll down to Stav registrací dle prioritních skupin
3. Hover on Na základě dosaženého věku

**Expected behavior**
Melo by tam byt cislo
![image](https://user-images.githubusercontent.com/24790694/121142550-61d6eb80-c83c-11eb-94a4-afe210345f51.png)

**Comment by jan-stanek** [comment]
Díky za upozornění, bohužel toto pochází už ze zdrojových dat - #394 #454

**Comment by MattyCZ** [comment]
Sakra, tak nějak jsem si myslel že ne, co se dá dělat. Pokud můžete tak to pošlete jim, tady je to asi na close.

**Comment by msusicky** [comment]
Presne tak, jde o spatny navrh na strane zdrojoveho systemu a tato data na nasi strane upravovat nebudeme. (mohli bychom vymazat zavorku, ale mame ted prioritnejsi veci + by bylo riziko zmen na jejich strane)
