### ISSUE TITLE
Souhrnné statistiky očkování

### ISSUE THREAD

**Issue by jan-bubenicek** [msusicky/ockovani-covid#468]
Zdravím,
v celkovém přehledu na stránce https://ockovani.opendatalab.cz/statistiky se nemůžu dopočítat správného počtu dávek, buď mi něco uniká, nebo je v datech někde problém. 
![image](https://user-images.githubusercontent.com/72620965/121322904-a8494a80-c90f-11eb-8116-3b67b6e3a686.png)

Uvažuji takto:
1 916 099 lidí má termín, z toho 1 558 997 lidí čeká na druhý termín (= má za sebou prvním očkování).
Dále
4 303 854 lidí dostalo alespoň 1 dávku z toho 1 852 757 má ukončení očkování (v tom by měli být i jednodávkové Jensen, kterých je cca 100 000) tedy 2 451 097 lidí dostalo jednu dávku ale ještě nedostalo druhou dávku. I při započtení Jensen je to cca 2 351 097. Na druhý termín však čeká pouze 1 558 997. Ve statistikách se tedy někde ztratilo zhruba 800 000 lidí. 

Jde o problém ÚZIS, zpracování dat, nebo to špatně čtu?
Děkuji za dobrou práci.

**Comment by msusicky** [comment]
Je to jednoduché, bohužel - problém v datech. Čekající na druhou dávku počítáme jen z rezervačního systému, ale dataset, který nám posílají, obsahuje jen 30 dní dopředně. Je to reklamované, asi na to zapomněli, tak jsem to dnes poslal znovu na NAKIT.
Tzn. nevidíme 10 dnů rezervací, tj. cca těch 800 000 lidí, plus AstraZenecu.
Není to ale snad natolik zásadní, abychom všechna čísla stáhnuli.

**Comment by jan-bubenicek** [comment]
jasně, díky za vysvětlení.
