### ISSUE TITLE
Špatné názvy prioritních skupin

### ISSUE THREAD

**Issue by jirijursa** [msusicky/ockovani-covid#471]
U krajů i jednotlivých očkovacích míst se v sekci "stav registrací" špatně zobrazují popisky u prioritní skupiny. 
Jsou tam popisky typu: "OccupationGroupAgeName". 
Nevím zda je to takto už v zdrojových datech nebo nedošlo k překladu při importu na web.

**Comment by msusicky** [comment]
Zase ten UZIS

**Comment by msusicky** [comment]
Omlouvám se UZISu, problém je na straně NAKIT - dělají na tom prý od rána, tak uvidíme. Pokud to večer nebude, tak uděláme workaround.

**Comment by msusicky** [comment]
Will be replaced based on the following table:
 OccupationGroupChronic2Name - Osoba s chronickým onemocněním – druhá skupina
 OccupationGroupAcademicStaffName - Akademický pracovník VŠ
 OccupationGroupArmyName - Zaměstnanci Ministerstva obrany
 OccupationGroupChronicName - Osoba s chronickým onemocněním
 OccupationGroupMedicalWorkerName - Zdravotnický pracovník dle §76 a §77 zákona 372/2011  Sb.
 OccupationGroupCriticalInfrastructureName - Kritická infrastruktura
 OccupationGroupTHPWorkersName - Technicko hospodářští pracovníci ve zdravotnických zařízeních
 OccupationGroupAgeName - Na základě dosaženého věku
 OccupationGroupSelfPayerName - samoplátce?
 neuvedeno -  neuvedeno
 OccupationGroupSocialWorkerName - Pracovník v sociálních službách
 OccupationGroupNonMedicalStaffName - Nezdravotničtí pracovníci podílející se na poskytování zdravotní péče a péče o
covid-19 pozitivní osoby
 Pedagogický pracovník/nepedagogický zaměstnanec
 OccupationGroupCaringPersonName - Osoba pečující o osobu v III. nebo IV. stupni závislosti
