### ISSUE TITLE
Kapacita druhé dávky

### ISSUE THREAD

**Issue by jan-bubenicek** [msusicky/ockovani-covid#479]
Dobrý den,
narazil jsem na zvláštní čísla u kapacity druhé dávky pro dnešní den, hádám že se změnily vstupní data.
![image](https://user-images.githubusercontent.com/72620965/122527408-93f60380-d01b-11eb-9e6a-d72dea7b5f70.png)

Díky za vaši práci.

**Comment by msusicky** [comment]
Zapomněli jsme odpovědět - diskutováno se zdrojem dat a pochopili jsme, že je komplikované donutit provozovatele zadávat relevantní hodnoty. Aspoň, že to platí pro druhé dávky...
