### ISSUE TITLE
Vylepsit UI, aby to pekne vypadalo

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#5]

**Comment by msusicky** [comment]
Almost done, thanks

**Comment by jan-stanek** [comment]
Proposals:
- [ ] remove background behind the table
- [ ] remove links to the same page
- [ ] sum of capacities is little bit misleading since we fetch only upcoming n days

**Comment by jan-stanek** [comment]
done in #26

**Comment by msusicky** [comment]
Fulfilled
