### ISSUE TITLE
Show some basic statistics for people

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#612]
We have quite good dataset from which we can compute the probability that someone will be on upv, ecmo, oxygen...
It can be used as an argument to vaccine or not...

**Comment by jan-stanek** [comment]
Fetcher should be ready https://github.com/msusicky/ockovani-covid/blob/develop/app/fetcher/hospital_analysis_fetcher.py

**Comment by jan-stanek** [comment]
Request from twitter for similar stats: https://twitter.com/RomanBartos2/status/1469201878391169024?s=20
