### ISSUE TITLE
Add link to GitHub repo to the web

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#63]

**Comment by hroncok** [comment]
Is it possible that the link is now gone? I found this repo by chance, had no idea it existed.

**Comment by msusicky** [comment]
It is not :) <no offense>Users are typically blind.</no offense>

![image](https://user-images.githubusercontent.com/1258380/122918066-02f69380-d35f-11eb-8052-57447bb322f7.png)

**Comment by hroncok** [comment]
Thanks! None taken, I was searching in the footer :)

**Comment by msusicky** [comment]
Maybe this is a feature request (but I don't expect that so many users are desperately waiting for our repo :)

**Comment by hroncok** [comment]
I you let me, I can send a PR to add a GH link to the footer :)

**Comment by msusicky** [comment]
No problem, any help appreciated :)

**Comment by hroncok** [comment]
Sorry I didn't get to this :(

**Comment by jan-stanek** [comment]
It'll be in the navbar, I hope it's ok :)

**Comment by hroncok** [comment]
Awesome, thanks!
