### ISSUE TITLE
AKTUALIZACE DAT

### ISSUE THREAD

**Issue by mxdpeep** [msusicky/ockovani-covid#806]
Čas poslední aktualizace: so 08. 07. 05:47. POZOR! - Aktualizace webu byla 8. 7. 2023 ukončena.

Nemohla by být opět spuštěna aktualizace?
Budou nás čekat páté a možná i šesté dávky vakcín proti omicronu BA.4 a BA.5.

**Comment by msusicky** [comment]
Mohu poprosit o zprávu o těch 5 a 6 dávkách?
Po zkušenosti se 4. dávkami mi přijde, že zájem nebude velký, ale nevylučuju variantu, že se pletu. 
Zkusím zjistit možnosti hostingu, to je největší blocker - bylo to na AWSku, ale to je teď zavřený.

**Comment by mxdpeep** [comment]
Zjistím detaily očkování 💉 v Brně, jak to s tím je.

Hosting mohu nabídnout zdarma náš (GS CLOUD Ltd.) ve Finsku, ale je nutné,
aby to běželo jako Docker kontejner, cron volání, web výstup jako Apache
TLS proxy skrz Cloudflare.

Což nevím, zda můžeš zajistit...

Filip Oščádal 🍀📱

**Comment by msusicky** [comment]
On to není ve skutečnosti hosting, ale jen jendou denně na cca hodinu pustit aplikační server, který stáhne data z UZIS (bohužel zatím neudělali ořez, takže se stále stahuje všechno :( ), zpracuje je do PGDB a vygeneruje stránky, které pak pushne do gitu. Hosting sám běží jako github pages ;)
předtím jsme to orchestrovali z github actions, ale to by se dalo vyřešit prostým cronem a jestli se to v některý den neprovede, tak se svět nezboří.

**Comment by mxdpeep** [comment]
když mi z toho uděláš Docker image, tak ti ho můžu prdnout na náš server > sys.gscloud.cz

**Comment by msusicky** [comment]
Dobre, v tomhle tydnu na to kouknu. zkusim se soucasne domluvit s UZIS, jestli by nechteli zacit delat datasety jen 2023 a novejsi. Ted bychom tam zbytecne denne otaceli GB

**Comment by msusicky** [comment]
Nezapomnel jsem, jen se pridaly zdravotni komplikace a fakt, ze jsme si nezamkli verze balicku a od posledne vyslo vazne hodne aktualizaci, vcetne major verzi

**Comment by msusicky** [comment]
Tak máme první pilot verzi, chyby prosím přes issues, pár stránek ještě hlásí 500, ale základní statistiky apod jedou
