### ISSUE TITLE
Improve statistics page UI

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#83]

**Comment by aditya28sarin** [comment]
can you assign me this issue?

**Comment by msusicky** [comment]
> can you assign me this issue?

Yes, but currently there is no description yet. At the moment we do a bigger shift because new opendata source is available.

**Comment by jan-stanek** [comment]
I wanted to:

- [ ] add sum for the first table
- [ ] align numbers and dates to right
- [ ] format dates as in the rest of the app
- [ ] remove line break before date in the text

**Comment by zachyunl** [comment]
Hi,
could you add interactive chart for first table with daily details? Type vaccine, "přislo", "vyočkováno" and "rozdíl".

**Comment by msusicky** [comment]
@vpokorny just fyi -> it is a little bit tricky to compute that, just let me know if you will have any questions

**Comment by jan-stanek** [comment]
@zachyunl separated issue was created for the graph #193
