### ISSUE TITLE
Perhaps more explanation for the data

### ISSUE THREAD

**Issue by j-maly** [msusicky/ockovani-covid#89]
I would appreciate a bit more information around the raw data presented, tooltips for columns, short description for each table. 

https://msusicky.github.io/ockovani-covid/misto/c8e549b8-aafb-4b4c-ae3b-b1ccee70513f - what is the meaning of the third column in the second table (Stav registrací > Poměr)?

Is it possible to show how many people were vaccinated every day? If so, can it be broken down into groups too?

**Comment by msusicky** [comment]
Good ideas definitely! This have my vote and if you or anyone else would like to contribute, it will be welcomed!
(otherwise we can expect this delivery ~ weekend)

**Comment by msusicky** [comment]
About the tooltips - check web in 20 minutes -> I've added a lot of tooltips. Poměr is described now and in tooltip you can see source data.

**Comment by msusicky** [comment]
No reaction -> closing
