### ISSUE TITLE
Idea - reservation - compute date of assignment

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#90]
In data there is a flag if registered person has reservation or not. But there is no date of the assignement. Makes sense to compute it from today and yesterday data and put it as a result. Maybe to realize it with trigger ?

Plus -> see how long does it take to obtain a reservation. -> powerful metric

**Comment by jan-stanek** [comment]
Should have higher priority we are losing data

**Comment by msusicky** [comment]
One remark -> there are a lot of people that don't like to reserve / ghosts. It is not sure how many 80+ would still like to reserve. Take care about it.

**Comment by jan-stanek** [comment]
Do we really need this? It's almost the same as date of reservation and effort/gain is very low

**Comment by msusicky** [comment]
Looks that it is not necessary.
