### ISSUE TITLE
Move to the new domain - ockovani.opendatalab.cz

### ISSUE THREAD

**Issue by msusicky** [msusicky/ockovani-covid#91]
To have better URL we'd decided to move under OpenDataLab (@msusicky is one of the leader)
It is already active, but now only redirecting to old repo.

- [x] Prepare branch with working menu links etc
- [x] Have a message on the intro page about move
- [x] Change github pusher
- [x] Have both working for 2 days - weekend
- [x] Do a redirect from the old repo

**Comment by jan-stanek** [comment]
Please add redirect from http to https version

**Comment by jan-stanek** [comment]
Current page highlighting in menu doesn't work there

**Comment by jan-stanek** [comment]
Enforce HTTPS in github pages config did the job

**Comment by jan-stanek** [comment]
Current page highlighting fixed in #107

**Comment by msusicky** [comment]
Fixed, old web published with links to the new one
