### ISSUE TITLE
Github actions pipeline

### ISSUE THREAD

**Issue by jan-stanek** [msusicky/ockovani-covid#96]
- [x] check if main and develop branches are in sync (merges from develop will not bring conflicts)
- [x] check if main and develop are protected
- [x] improve logging and exit code of used scripts
- [x] implement pipeline for main update - deploy to prd environment and update static pages
- [x] implement pipeline for develop update - deploy to test environment
- [x] implement scheduled pipeline for data update

Depends on: #97

**Comment by msusicky** [comment]
Done
